// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKY3WDraCdRReD0CBWo080tmfER0Qz1qs',
    appId: '1:618649720334:web:fd7338946291eb69454e5f',
    messagingSenderId: '618649720334',
    projectId: 'product-manage-app',
    authDomain: 'product-manage-app.firebaseapp.com',
    storageBucket: 'product-manage-app.appspot.com',
    measurementId: 'G-MM3W01JLQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCROiiQGi5xgc5XX_6siKkiG3sFtwNHWvA',
    appId: '1:618649720334:android:638531c0fcf82b5a454e5f',
    messagingSenderId: '618649720334',
    projectId: 'product-manage-app',
    storageBucket: 'product-manage-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgaFLL0-WEFY3k6zh1IyesTjW-carp7BI',
    appId: '1:618649720334:ios:e16db1a24f960530454e5f',
    messagingSenderId: '618649720334',
    projectId: 'product-manage-app',
    storageBucket: 'product-manage-app.appspot.com',
    iosBundleId: 'com.example.productManageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgaFLL0-WEFY3k6zh1IyesTjW-carp7BI',
    appId: '1:618649720334:ios:e16db1a24f960530454e5f',
    messagingSenderId: '618649720334',
    projectId: 'product-manage-app',
    storageBucket: 'product-manage-app.appspot.com',
    iosBundleId: 'com.example.productManageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKY3WDraCdRReD0CBWo080tmfER0Qz1qs',
    appId: '1:618649720334:web:016e692c119c5c26454e5f',
    messagingSenderId: '618649720334',
    projectId: 'product-manage-app',
    authDomain: 'product-manage-app.firebaseapp.com',
    storageBucket: 'product-manage-app.appspot.com',
    measurementId: 'G-C1C5D5HRR2',
  );
}
